function B = compute_B_full(x1,x2,x3,x4,x5,x6,x7,x8,u1,u2)
%COMPUTE_B_FULL
%    B = COMPUTE_B_FULL(X1,X2,X3,X4,X5,X6,X7,X8,U1,U2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-Jun-2019 10:46:56

B = reshape([0.0,0.0,0.0,0.0,0.0,0.0,1.0e1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e1],[8,2]);
