function dx = system_f(x, u)
    c = Constants();
    
    dx = system_f_with_params(x, u, ...
        c.m_c, c.m_h, c.l_c, c.l_h, c.l_p, c.d_c, c.d_h, ...
        c.mup, c.mue, c.mul, ...
        c.T_w, c.K_w, ...
        c.p1, c.q1, c.p2, c.q2, ...
        c.J_m, c.K_m);
end

