function B = compute_B(x1,x2,x3,x4,x5,x6,u1,u2)
%COMPUTE_B
%    B = COMPUTE_B(X1,X2,X3,X4,X5,X6,U1,U2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    17-May-2019 11:32:28

t2 = cos(x1);
t3 = t2.*5.710696133858716e-1;
t4 = cos(x2);
t5 = sin(x1);
t6 = t4.*t5.*5.47057093739832e-1;
B = reshape([0.0,0.0,0.0,3.602824614497767,t3,t6,0.0,0.0,0.0,-3.602824614497767,t3,t6],[6,2]);
